// <auto-generated />
using System;
using Jewelry.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jewelry.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201116064752_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Jewelry.Infrastructure.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<long>("JewelryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SoldDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JewelryId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Jewelry.Infrastructure.Models.Jewelry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jewelries");
                });

            modelBuilder.Entity("Jewelry.Infrastructure.Models.Client", b =>
                {
                    b.HasOne("Jewelry.Infrastructure.Models.Jewelry", "Jewelry")
                        .WithMany("Clients")
                        .HasForeignKey("JewelryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jewelry");
                });

            modelBuilder.Entity("Jewelry.Infrastructure.Models.Jewelry", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
